version: "3"

networks:
  devel-network:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16

services:
  spark-master:
    image: bde2020/spark-master:2.4.0-hadoop2.7
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      devel-network:
        ipv4_address: 172.27.1.10

  spark-worker-1:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker-1
    environment:
      - SPARK_LOCAL_IP=spark-worker-1
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    env_file:
      - ./env/worker.sh
    volumes:
      - ./executors/worker-data:/opt/spark-data
      - ./executors/worker-app:/opt/spark-apps
    networks:
      devel-network:
        ipv4_address: 172.27.1.11

  spark-worker-2:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker-2
    environment:
      - SPARK_LOCAL_IP=spark-worker-2
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    env_file:
      - ./env/worker.sh
    volumes:
      - ./executors/worker-data:/opt/spark-data
      - ./executors/worker-app:/opt/spark-apps
    networks:
      devel-network:
        ipv4_address: 172.27.1.12

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      devel-network:
        ipv4_address: 172.27.1.15

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_NUM_PARTITIONS: 12
      KAFKA_COMPRESSION_TYPE: gzip
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      KAFKA_JMX_PORT: 9091
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      devel-network:
        ipv4_address: 172.27.1.16

  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    hostname: akhq
    volumes:
      - ./env/application.yml:/app/application.yml
    ports:
      - "8079:8080"
    depends_on:
      - kafka
      - schema-registry
    networks:
      devel-network:
        ipv4_address: 172.27.1.20
  
  schema-registry:
    image: confluentinc/cp-schema-registry
    container_name: schema-registry
    depends_on:
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:9092"
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8085"
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO
    networks:
      devel-network:
        ipv4_address: 172.27.1.21